<?php

use CRM_Events_ExtensionUtil as E;

return [
  [
    'name' => 'CustomGroup_freiwillige_zusatzinfos',
    'entity' => 'CustomGroup',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'freiwillige_zusatzinfos',
        'table_name' => 'civicrm_value_freiwillige_zusatzinfos',
        'title' => E::ts('Zusätzliche Informationen für Freiwillige'),
        'extends' => 'Individual',
        'extends_entity_column_value' => [
          'Freiwillige',
        ],
        'style' => 'Inline',
      ],
      'match' => [
        'name',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_freiwillige_zusatzinfos_CustomField_freiwillige_freiwilligenkennung',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'freiwillige_zusatzinfos',
        'name' => 'freiwillige_freiwilligenkennung',
        'label' => E::ts('Freiwilligenkennung'),
        'html_type' => 'Text',
        'is_searchable' => TRUE,
        'column_name' => 'freiwillige_freiwilligenkennung',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_regionalstellen',
    'entity' => 'OptionGroup',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'regionalstellen',
        'title' => E::ts('Regionalstellen'),
        'description' => E::ts('Regionalstellen'),
        'option_value_fields' => [
          'name',
          'label',
          'description',
        ],
      ],
      'match' => [
        'name',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_regionalstellen_OptionValue_regionalstelle_s_d',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'regionalstellen',
        'label' => E::ts('Süd'),
        'value' => '1',
        'name' => 'regionalstelle_s_d',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_regionalstellen_OptionValue_regionalstelle_ost',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'regionalstellen',
        'label' => E::ts('Ost'),
        'value' => '2',
        'name' => 'regionalstelle_ost',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_regionalstellen_OptionValue_regionalstelle_west',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'regionalstellen',
        'label' => E::ts('West'),
        'value' => '3',
        'name' => 'regionalstelle_west',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_regionalstellen_OptionValue_regionalstelle_tgd',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'regionalstellen',
        'label' => E::ts('TGD'),
        'value' => '4',
        'name' => 'regionalstelle_tgd',
        'is_default' => TRUE,
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_freiwillige_zusatzinfos_CustomField_freiwillige_regionalstelle',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'freiwillige_zusatzinfos',
        'name' => 'freiwillige_regionalstelle',
        'label' => E::ts('Regionalstelle'),
        'html_type' => 'Select',
        'is_searchable' => TRUE,
        'column_name' => 'freiwillige_regionalstelle',
        'option_group_id.name' => 'regionalstellen',
        'serialize' => 1,
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_freiwillige_zusatzinfos_CustomField_freiwillige_regionalstellenbetreuerin',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'freiwillige_zusatzinfos',
        'name' => 'freiwillige_regionalstellenbetreuerin',
        'label' => E::ts('RS-BetreuerIn'),
        'data_type' => 'ContactReference',
        'html_type' => 'Autocomplete-Select',
        'is_searchable' => TRUE,
        'column_name' => 'freiwillige_regionalstellenbetre',
        'filter' => 'action=lookup&group=2',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_freiwillige_zusatzinfos_CustomField_freiwillige_nationalit_t',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'freiwillige_zusatzinfos',
        'name' => 'freiwillige_nationalit_t',
        'label' => E::ts('Nationalität'),
        'html_type' => 'Text',
        'is_searchable' => TRUE,
        'column_name' => 'freiwillige_nationalit_t',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_freiwillige_arbeitszeit',
    'entity' => 'OptionGroup',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'freiwillige_arbeitszeit',
        'title' => E::ts('Arbeitszeit'),
        'description' => E::ts('Arbeitszeit von Freiwilligen'),
        'option_value_fields' => [
          'name',
          'label',
          'description',
        ],
      ],
      'match' => [
        'name',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_freiwillige_arbeitszeit_OptionValue_Englisch',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'freiwillige_arbeitszeit',
        'label' => E::ts('Teilzeit'),
        'value' => '2',
        'name' => 'Englisch',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_freiwillige_arbeitszeit_OptionValue_Deutsch',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'freiwillige_arbeitszeit',
        'label' => E::ts('Vollzeit'),
        'value' => '1',
        'name' => 'Deutsch',
        'is_default' => TRUE,
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_freiwillige_zusatzinfos_CustomField_freiwillige_arbeitszeit',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'freiwillige_zusatzinfos',
        'name' => 'freiwillige_arbeitszeit',
        'label' => E::ts('Arbeitszeit'),
        'html_type' => 'Select',
        'is_searchable' => TRUE,
        'is_active' => FALSE,
        'column_name' => 'freiwillige_arbeitszeit',
        'option_group_id.name' => 'freiwillige_arbeitszeit',
        'serialize' => 1,
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_freiwillige_zusatzinfos_CustomField_freiwillige_stundenzahl',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'freiwillige_zusatzinfos',
        'name' => 'freiwillige_stundenzahl',
        'label' => E::ts('Wochenstunden'),
        'html_type' => 'Text',
        'is_searchable' => TRUE,
        'is_active' => FALSE,
        'column_name' => 'freiwillige_stundenzahl',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_freiwillige_zusatzinfos_CustomField_freiwillige_regelstunden',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'freiwillige_zusatzinfos',
        'name' => 'freiwillige_regelstunden',
        'label' => E::ts('Regelstunden'),
        'html_type' => 'Text',
        'is_searchable' => TRUE,
        'is_active' => FALSE,
        'column_name' => 'freiwillige_regelstunden',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_freiwillige_bevorzugte_sprache',
    'entity' => 'OptionGroup',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'freiwillige_bevorzugte_sprache',
        'title' => E::ts('Sprachkenntnisse'),
        'description' => E::ts('Sprachkenntnisse von Freiwilligen'),
        'option_value_fields' => [
          'name',
          'label',
          'description',
        ],
      ],
      'match' => [
        'name',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_freiwillige_bevorzugte_sprache_OptionValue_Chinesisch',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'freiwillige_bevorzugte_sprache',
        'label' => E::ts('Chinesisch'),
        'value' => '10',
        'name' => 'Chinesisch',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_freiwillige_bevorzugte_sprache_OptionValue_Porutgiesisch',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'freiwillige_bevorzugte_sprache',
        'label' => E::ts('Porutgiesisch'),
        'value' => '11',
        'name' => 'Porutgiesisch',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_freiwillige_bevorzugte_sprache_OptionValue_T_rkisch',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'freiwillige_bevorzugte_sprache',
        'label' => E::ts('Türkisch'),
        'value' => '8',
        'name' => 'T_rkisch',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_freiwillige_bevorzugte_sprache_OptionValue_Polnisch',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'freiwillige_bevorzugte_sprache',
        'label' => E::ts('Polnisch'),
        'value' => '9',
        'name' => 'Polnisch',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_freiwillige_bevorzugte_sprache_OptionValue_Russisch',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'freiwillige_bevorzugte_sprache',
        'label' => E::ts('Russisch'),
        'value' => '6',
        'name' => 'Russisch',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_freiwillige_bevorzugte_sprache_OptionValue_Arabisch',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'freiwillige_bevorzugte_sprache',
        'label' => E::ts('Arabisch'),
        'value' => '7',
        'name' => 'Arabisch',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_freiwillige_bevorzugte_sprache_OptionValue_Franz_sisch',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'freiwillige_bevorzugte_sprache',
        'label' => E::ts('Französisch'),
        'value' => '5',
        'name' => 'Franz_sisch',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_freiwillige_bevorzugte_sprache_OptionValue_Italienisch',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'freiwillige_bevorzugte_sprache',
        'label' => E::ts('Italienisch'),
        'value' => '4',
        'name' => 'Italienisch',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_freiwillige_bevorzugte_sprache_OptionValue_Spanisch',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'freiwillige_bevorzugte_sprache',
        'label' => E::ts('Spanisch'),
        'value' => '3',
        'name' => 'Spanisch',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_freiwillige_bevorzugte_sprache_OptionValue_Englisch',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'freiwillige_bevorzugte_sprache',
        'label' => E::ts('Englisch'),
        'value' => '2',
        'name' => 'Englisch',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_freiwillige_bevorzugte_sprache_OptionValue_Deutsch',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'freiwillige_bevorzugte_sprache',
        'label' => E::ts('Deutsch'),
        'value' => '1',
        'name' => 'Deutsch',
        'is_default' => TRUE,
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_freiwillige_zusatzinfos_CustomField_freiwillige_bevorzugte_sprache',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'freiwillige_zusatzinfos',
        'name' => 'freiwillige_bevorzugte_sprache',
        'label' => E::ts('Bevorzugte Sprache'),
        'html_type' => 'Select',
        'is_searchable' => TRUE,
        'column_name' => 'freiwillige_bevorzugte_sprache',
        'option_group_id.name' => 'freiwillige_bevorzugte_sprache',
        'serialize' => 1,
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_freiwillige_deutschkenntnisse',
    'entity' => 'OptionGroup',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'freiwillige_deutschkenntnisse',
        'title' => E::ts('Deutschkenntnisse'),
        'description' => E::ts('Deutschkenntnisse'),
        'option_value_fields' => [
          'name',
          'label',
          'description',
        ],
      ],
      'match' => [
        'name',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_freiwillige_deutschkenntnisse_OptionValue_keine',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'freiwillige_deutschkenntnisse',
        'label' => E::ts('keine'),
        'value' => '4',
        'name' => 'keine',
        'is_default' => TRUE,
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_freiwillige_deutschkenntnisse_OptionValue_gut',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'freiwillige_deutschkenntnisse',
        'label' => E::ts('gut'),
        'value' => '2',
        'name' => 'gut',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_freiwillige_deutschkenntnisse_OptionValue_gering',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'freiwillige_deutschkenntnisse',
        'label' => E::ts('gering'),
        'value' => '3',
        'name' => 'gering',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_freiwillige_deutschkenntnisse_OptionValue_sehr_gut',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'freiwillige_deutschkenntnisse',
        'label' => E::ts('sehr gut'),
        'value' => '1',
        'name' => 'sehr_gut',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_freiwillige_zusatzinfos_CustomField_freiwillige_deutschkenntnisse',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'freiwillige_zusatzinfos',
        'name' => 'freiwillige_deutschkenntnisse',
        'label' => E::ts('Deutschkenntnisse'),
        'html_type' => 'Select',
        'is_searchable' => TRUE,
        'column_name' => 'freiwillige_deutschkenntnisse',
        'option_group_id.name' => 'freiwillige_deutschkenntnisse',
        'serialize' => 1,
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_freiwillige_zusatzinfos_CustomField_freiwillige_seminar_tage_pflicht',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'freiwillige_zusatzinfos',
        'name' => 'freiwillige_seminar_tage_pflicht',
        'label' => E::ts('zu leistende Seminar-Tage'),
        'data_type' => 'Int',
        'html_type' => 'Text',
        'is_searchable' => TRUE,
        'column_name' => 'freiwillige_seminar_tage_pflicht',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_freiwillige_zusatzinfos_CustomField_freiwillige_politische_bildungstage',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'freiwillige_zusatzinfos',
        'name' => 'freiwillige_politische_bildungstage',
        'label' => E::ts('Politische Bildungstage'),
        'data_type' => 'Int',
        'html_type' => 'Text',
        'is_searchable' => TRUE,
        'is_search_range' => TRUE,
        'column_name' => 'freiwillige_politische_bildungst',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_freiwillige_zusatzinfos_CustomField_freiwillige_seminar_tage_gebucht',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'freiwillige_zusatzinfos',
        'name' => 'freiwillige_seminar_tage_gebucht',
        'label' => E::ts('gebuchte Seminar-Tage'),
        'data_type' => 'Int',
        'html_type' => 'Text',
        'is_searchable' => TRUE,
        'is_search_range' => TRUE,
        'is_view' => TRUE,
        'column_name' => 'freiwillige_seminar_tage_gebucht',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_freiwillige_zusatzinfos_CustomField_freiwillige_seminar_tage_gebucht_online',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'freiwillige_zusatzinfos',
        'name' => 'freiwillige_seminar_tage_gebucht_online',
        'label' => E::ts('gebuchte Online Seminar-Tage'),
        'data_type' => 'Int',
        'html_type' => 'Text',
        'is_searchable' => TRUE,
        'is_search_range' => TRUE,
        'is_view' => TRUE,
        'column_name' => 'freiwillige_seminar_tage_gebucht_online',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_freiwillige_zusatzinfos_CustomField_freiwillige_seminar_tage_gebucht_praesenz',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'freiwillige_zusatzinfos',
        'name' => 'freiwillige_seminar_tage_gebucht_praesenz',
        'label' => E::ts('gebuchte Präsenz Seminar-Tage'),
        'data_type' => 'Int',
        'html_type' => 'Text',
        'is_searchable' => TRUE,
        'is_search_range' => TRUE,
        'is_view' => TRUE,
        'column_name' => 'freiwillige_seminar_tage_gebucht_praesenz',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_freiwillige_zusatzinfos_CustomField_freiwillige_seminar_tage_geleistet',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'freiwillige_zusatzinfos',
        'name' => 'freiwillige_seminar_tage_geleistet',
        'label' => E::ts('verbrauchte Seminar-Tage'),
        'data_type' => 'Int',
        'html_type' => 'Text',
        'is_searchable' => TRUE,
        'is_search_range' => TRUE,
        'help_post' => E::ts('Hier werden sowohl teilgenommene Tage, solche zukünftiger Anmeldungen mit positivem Status als auch entschuldigte Fehltage berücksichtigt.'),
        'is_view' => TRUE,
        'column_name' => 'freiwillige_seminar_tage_geleist',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_freiwillige_zusatzinfos_CustomField_freiwillige_seminar_tage_offen',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'freiwillige_zusatzinfos',
        'name' => 'freiwillige_seminar_tage_offen',
        'label' => E::ts('offene Seminar-Tage'),
        'data_type' => 'Int',
        'html_type' => 'Text',
        'is_searchable' => TRUE,
        'is_search_range' => TRUE,
        'is_view' => TRUE,
        'column_name' => 'freiwillige_seminar_tage_offen',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_freiwillige_zusatzinfos_CustomField_freiwillige_gesamtfehltage_entschuldigt',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'freiwillige_zusatzinfos',
        'name' => 'freiwillige_gesamtfehltage_entschuldigt',
        'label' => E::ts('Gesamtfehltage entschuldigt'),
        'data_type' => 'Int',
        'html_type' => 'Text',
        'is_searchable' => TRUE,
        'is_search_range' => TRUE,
        'is_view' => TRUE,
        'column_name' => 'freiwillige_gesamtfehltage_entsc',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_freiwillige_zusatzinfos_CustomField_freiwillige_gesamtfehltage_unentschuldigt',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'freiwillige_zusatzinfos',
        'name' => 'freiwillige_gesamtfehltage_unentschuldigt',
        'label' => E::ts('Gesamtfehltage unentschuldigt'),
        'data_type' => 'Int',
        'html_type' => 'Text',
        'is_searchable' => TRUE,
        'is_search_range' => TRUE,
        'is_view' => TRUE,
        'column_name' => 'freiwillige_gesamtfehltage_unent',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
];
