<?php

use CRM_Events_ExtensionUtil as E;

return [
  [
    'name' => 'CustomGroup_einsatz_zusatzinfos',
    'entity' => 'CustomGroup',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'einsatz_zusatzinfos',
        'table_name' => 'civicrm_value_einsatz_zusatzinfos',
        'title' => E::ts('Zusätzliche Informationen zum Einsatz von Freiwilligen'),
        'extends' => 'Relationship',
        'extends_entity_column_value:name' => [
          'ist Freiwillige* bei',
        ],
        'style' => 'Inline',
      ],
      'match' => [
        'name',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_einsatz_status',
    'entity' => 'OptionGroup',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'einsatz_status',
        'title' => E::ts('Status der Einsätze'),
        'description' => E::ts('Status der Einsätze'),
        'option_value_fields' => [
          'name',
          'label',
          'description',
        ],
      ],
      'match' => [
        'name',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_einsatz_status_OptionValue_abgebrochen',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'einsatz_status',
        'label' => E::ts('Abgebrochen'),
        'value' => '6',
        'name' => 'abgebrochen',
        'is_default' => TRUE,
        'is_active' => FALSE,
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_einsatz_status_OptionValue_abgesagt',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'einsatz_status',
        'label' => E::ts('Abgesagt'),
        'value' => '5',
        'name' => 'abgesagt',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_einsatz_status_OptionValue_ausgeschieden',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'einsatz_status',
        'label' => E::ts('Ausgeschieden'),
        'value' => '4',
        'name' => 'ausgeschieden',
        'is_active' => FALSE,
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_einsatz_status_OptionValue_beendet',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'einsatz_status',
        'label' => E::ts('Beendet'),
        'value' => '3',
        'name' => 'beendet',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_einsatz_status_OptionValue_laufend',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'einsatz_status',
        'label' => E::ts('Laufend'),
        'value' => '2',
        'name' => 'laufend',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_einsatz_status_OptionValue_geplant',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'einsatz_status',
        'label' => E::ts('Geplant'),
        'value' => '1',
        'name' => 'geplant',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_einsatz_zusatzinfos_CustomField_einsatz_status',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'einsatz_zusatzinfos',
        'name' => 'einsatz_status',
        'label' => E::ts('Status'),
        'html_type' => 'Select',
        'is_searchable' => TRUE,
        'column_name' => 'einsatz_status',
        'option_group_id.name' => 'einsatz_status',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_einsatz_zusatzinfos_CustomField_Wochenstunden',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'einsatz_zusatzinfos',
        'name' => 'Wochenstunden',
        'label' => E::ts('Wochenstunden'),
        'data_type' => 'Float',
        'html_type' => 'Text',
        'is_searchable' => TRUE,
        'is_search_range' => TRUE,
        'is_active' => FALSE,
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'wochenstunden',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_einsatz_zusatzinfos_CustomField_Regelstunden',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'einsatz_zusatzinfos',
        'name' => 'Regelstunden',
        'label' => E::ts('Regelstunden'),
        'data_type' => 'Float',
        'html_type' => 'Text',
        'is_searchable' => TRUE,
        'is_search_range' => TRUE,
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'regelstunden',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_einsatz_zusatzinfos_CustomField_einsatz_stundenzahl',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'einsatz_zusatzinfos',
        'name' => 'einsatz_stundenzahl',
        'label' => E::ts('Stundenzahl'),
        'html_type' => 'Text',
        'is_searchable' => TRUE,
        'column_name' => 'einsatz_stundenzahl',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_einsatz_voll_oder_teilzeit',
    'entity' => 'OptionGroup',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'einsatz_voll_oder_teilzeit',
        'title' => E::ts('Voll- oder Teilzeit'),
        'description' => E::ts('Voll- oder Teilzeit'),
        'option_value_fields' => [
          'name',
          'label',
          'description',
        ],
      ],
      'match' => [
        'name',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_einsatz_voll_oder_teilzeit_OptionValue_teilzeit',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'einsatz_voll_oder_teilzeit',
        'label' => E::ts('Teilzeit'),
        'value' => '2',
        'name' => 'teilzeit',
        'is_default' => TRUE,
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_einsatz_voll_oder_teilzeit_OptionValue_vollzeit',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'einsatz_voll_oder_teilzeit',
        'label' => E::ts('Vollzeit'),
        'value' => '1',
        'name' => 'vollzeit',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_einsatz_zusatzinfos_CustomField_einsatz_voll_oder_teilzeit',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'einsatz_zusatzinfos',
        'name' => 'einsatz_voll_oder_teilzeit',
        'label' => E::ts('Voll- oder Teilzeit'),
        'html_type' => 'Select',
        'is_searchable' => TRUE,
        'column_name' => 'einsatz_voll_oder_teilzeit',
        'option_group_id.name' => 'einsatz_voll_oder_teilzeit',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_einsatz_zusatzinfos_CustomField_einsatz_taschengeld',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'einsatz_zusatzinfos',
        'name' => 'einsatz_taschengeld',
        'label' => E::ts('Taschengeld'),
        'data_type' => 'Money',
        'html_type' => 'Text',
        'is_searchable' => TRUE,
        'column_name' => 'einsatz_taschengeld',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_einsatz_zusatzinfos_CustomField_einsatz_verpflegung',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'einsatz_zusatzinfos',
        'name' => 'einsatz_verpflegung',
        'label' => E::ts('Verpflegung'),
        'data_type' => 'Money',
        'html_type' => 'Text',
        'is_searchable' => TRUE,
        'column_name' => 'einsatz_verpflegung',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_einsatz_zusatzinfos_CustomField_einsatz_sonstige_leistungen',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'einsatz_zusatzinfos',
        'name' => 'einsatz_sonstige_leistungen',
        'label' => E::ts('sonstige Leistungen'),
        'data_type' => 'Money',
        'html_type' => 'Text',
        'is_searchable' => TRUE,
        'column_name' => 'einsatz_sonstige_leistungen',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_einsatz_zusatzinfos_CustomField_einsatz_sv_betrag',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'einsatz_zusatzinfos',
        'name' => 'einsatz_sv_betrag',
        'label' => E::ts('SV-Betrag'),
        'data_type' => 'Money',
        'html_type' => 'Text',
        'is_searchable' => TRUE,
        'column_name' => 'einsatz_sv_betrag',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_einsatz_zusatzinfos_CustomField_einsatz_dienstbescheinigung_erstellt',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'einsatz_zusatzinfos',
        'name' => 'einsatz_dienstbescheinigung_erstellt',
        'label' => E::ts('Dienstbescheinigung erstellt'),
        'data_type' => 'Boolean',
        'html_type' => 'Radio',
        'is_searchable' => TRUE,
        'column_name' => 'einsatz_dienstbescheinigung_erstellt',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_einsatz_zusatzinfos_CustomField_einsatz_bfd_vereinbarung_best_tigt',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'einsatz_zusatzinfos',
        'name' => 'einsatz_bfd_vereinbarung_best_tigt',
        'label' => E::ts('BFD-Vereinbarung bestätigt'),
        'data_type' => 'Boolean',
        'html_type' => 'Radio',
        'is_searchable' => TRUE,
        'column_name' => 'einsatz_bfd_vereinbarung_best_tigt',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_einsatz_zusatzinfos_CustomField_einsatz_verl_ngerungsbest_tigung',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'einsatz_zusatzinfos',
        'name' => 'einsatz_verl_ngerungsbest_tigung',
        'label' => E::ts('Verlängergung bestätigt'),
        'data_type' => 'Boolean',
        'html_type' => 'Radio',
        'is_searchable' => TRUE,
        'column_name' => 'einsatz_verl_ngerungsbest_tigung',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_einsatz_zusatzinfos_CustomField_einsatz_nderungsbest_tigung',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'einsatz_zusatzinfos',
        'name' => 'einsatz_nderungsbest_tigung',
        'label' => E::ts('Änderung bestätigt'),
        'data_type' => 'Boolean',
        'html_type' => 'Radio',
        'is_searchable' => TRUE,
        'column_name' => 'einsatz_nderungsbest_tigung',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_einsatz_zusatzinfos_CustomField_einsatz_k_ndigungsbest_tigung',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'einsatz_zusatzinfos',
        'name' => 'einsatz_k_ndigungsbest_tigung',
        'label' => E::ts('Kündigung bestätigt'),
        'data_type' => 'Boolean',
        'html_type' => 'Radio',
        'is_searchable' => TRUE,
        'column_name' => 'einsatz_k_ndigungsbest_tigung',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_einsatz_zusatzinfos_CustomField_einsatz_personalbogen_vorhanden',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'einsatz_zusatzinfos',
        'name' => 'einsatz_personalbogen_vorhanden',
        'label' => E::ts('Personalbogen vorhanden'),
        'data_type' => 'Boolean',
        'html_type' => 'Radio',
        'is_searchable' => TRUE,
        'column_name' => 'einsatz_personalbogen_vorhanden',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_einsatz_zusatzinfos_CustomField_einsatz_begr_ungsschreiben_raus',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'einsatz_zusatzinfos',
        'name' => 'einsatz_begr_ungsschreiben_raus',
        'label' => E::ts('Begrüßungsschreiben raus'),
        'data_type' => 'Boolean',
        'html_type' => 'Radio',
        'is_searchable' => TRUE,
        'column_name' => 'einsatz_begr_ungsschreiben_raus',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_einsatz_zusatzinfos_CustomField_einsatz_antrag_auf_f_rderbedarf',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'einsatz_zusatzinfos',
        'name' => 'einsatz_antrag_auf_f_rderbedarf',
        'label' => E::ts('Antrag auf Förderbedarf'),
        'data_type' => 'Boolean',
        'html_type' => 'Radio',
        'is_searchable' => TRUE,
        'column_name' => 'einsatz_antrag_auf_f_rderbedarf',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_einsatz_zusatzinfos_CustomField_einsatz_warten_auf_attest',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'einsatz_zusatzinfos',
        'name' => 'einsatz_warten_auf_attest',
        'label' => E::ts('Warten auf Attest'),
        'data_type' => 'Boolean',
        'html_type' => 'Radio',
        'is_searchable' => TRUE,
        'column_name' => 'einsatz_warten_auf_attest',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_einsatz_zusatzinfos_CustomField_einsatz_warten_auf_externe_seminarbescheinigung',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'einsatz_zusatzinfos',
        'name' => 'einsatz_warten_auf_externe_seminarbescheinigung',
        'label' => E::ts('Warten auf externe Seminarbescheinigung'),
        'data_type' => 'Boolean',
        'html_type' => 'Radio',
        'is_searchable' => TRUE,
        'column_name' => 'einsatz_warten_auf_externe_seminarbescheinigung',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_einsatz_zusatzinfos_CustomField_einsatz_fw_zeit_seminar',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'einsatz_zusatzinfos',
        'name' => 'einsatz_fw_zeit_seminar',
        'label' => E::ts('FW-Zeit-Seminar'),
        'data_type' => 'Boolean',
        'html_type' => 'Radio',
        'is_searchable' => TRUE,
        'column_name' => 'einsatz_fw_zeit_seminar',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_einsatz_zusatzinfos_CustomField_einsatz_kennenlerntelefonat_noch_offen',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'einsatz_zusatzinfos',
        'name' => 'einsatz_kennenlerntelefonat_noch_offen',
        'label' => E::ts('Seminarplanung abgeschlossen'),
        'data_type' => 'Boolean',
        'html_type' => 'Radio',
        'default_value' => '0',
        'is_searchable' => TRUE,
        'column_name' => 'einsatz_kennenlerntelefonat_noch_offen',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_einsatz_zusatzinfos_CustomField_einsatz_offene_r_ckmeldung',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'einsatz_zusatzinfos',
        'name' => 'einsatz_offene_r_ckmeldung',
        'label' => E::ts('offene Rückmeldung'),
        'data_type' => 'Boolean',
        'html_type' => 'Radio',
        'is_searchable' => TRUE,
        'column_name' => 'einsatz_offene_r_ckmeldung',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_einsatz_zusatzinfos_CustomField_einsatz_offener_konflikt',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'einsatz_zusatzinfos',
        'name' => 'einsatz_offener_konflikt',
        'label' => E::ts('offener Konflikt'),
        'data_type' => 'Boolean',
        'html_type' => 'Radio',
        'is_searchable' => TRUE,
        'column_name' => 'einsatz_offener_konflikt',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_einsatz_zusatzinfos_CustomField_einsatz_verk_rzt',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'einsatz_zusatzinfos',
        'name' => 'einsatz_verk_rzt',
        'label' => E::ts('Verkürzt'),
        'data_type' => 'Boolean',
        'html_type' => 'Radio',
        'is_searchable' => TRUE,
        'column_name' => 'einsatz_verk_rzt',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_einsatz_zusatzinfos_CustomField_einsatz_verl_ngert',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'einsatz_zusatzinfos',
        'name' => 'einsatz_verl_ngert',
        'label' => E::ts('Verlängert'),
        'data_type' => 'Boolean',
        'html_type' => 'Radio',
        'is_searchable' => TRUE,
        'column_name' => 'einsatz_verl_ngert',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_einsatz_zusatzinfos_CustomField_einsatz_ank_ndigung_verl_ngerung_verk_rzung',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'einsatz_zusatzinfos',
        'name' => 'einsatz_ank_ndigung_verl_ngerung_verk_rzung',
        'label' => E::ts('Ankündigung Verlängerung/Verkürzung'),
        'data_type' => 'Boolean',
        'html_type' => 'Radio',
        'is_searchable' => TRUE,
        'column_name' => 'einsatz_ank_ndigung_verl_ngerung',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_einsatz_zusatzinfos_CustomField_einsatz_dienstbescheinigung_da',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'einsatz_zusatzinfos',
        'name' => 'einsatz_dienstbescheinigung_da',
        'label' => E::ts('Dienstbescheinigung da'),
        'data_type' => 'Boolean',
        'html_type' => 'Radio',
        'is_searchable' => TRUE,
        'column_name' => 'einsatz_dienstbescheinigung_da',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_einsatz_zusatzinfos_CustomField_einsatz_zeugnisbest_tigung_da',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'einsatz_zusatzinfos',
        'name' => 'einsatz_zeugnisbest_tigung_da',
        'label' => E::ts('Zeugnisbestätigung da'),
        'data_type' => 'Boolean',
        'html_type' => 'Radio',
        'is_searchable' => TRUE,
        'column_name' => 'einsatz_zeugnisbest_tigung_da',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_einsatz_zusatzinfos_CustomField_einsatz_abschiedsmail_erhalten',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'einsatz_zusatzinfos',
        'name' => 'einsatz_abschiedsmail_erhalten',
        'label' => E::ts('Abschiedsmail erhalten'),
        'data_type' => 'Boolean',
        'html_type' => 'Radio',
        'is_searchable' => TRUE,
        'column_name' => 'einsatz_abschiedsmail_erhalten',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_einsatz_zusatzinfos_CustomField_einsatz_probemitgliedschaft_abgeschlossen',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'einsatz_zusatzinfos',
        'name' => 'einsatz_probemitgliedschaft_abgeschlossen',
        'label' => E::ts('Probemitgliedschaft abgeschlossen'),
        'data_type' => 'Boolean',
        'html_type' => 'Radio',
        'is_searchable' => TRUE,
        'column_name' => 'einsatz_probemitgliedschaft_abgeschlossen',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_einsatz_zusatzinfos_CustomField_Dienstzeitbescheinigung',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'einsatz_zusatzinfos',
        'name' => 'Dienstzeitbescheinigung',
        'label' => E::ts('Dienstzeitbescheinigung'),
        'data_type' => 'File',
        'html_type' => 'File',
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'dienstzeitbescheinigung',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
];
