<?php

use CRM_Events_ExtensionUtil as E;

return [
  [
    'name' => 'CustomGroup_seminar_zusatzinfo',
    'entity' => 'CustomGroup',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'seminar_zusatzinfo',
        'table_name' => 'civicrm_value_seminar_zusatzinfo',
        'title' => E::ts('Zusätzliche Informationen für Seminare'),
        'extends' => 'Event',
        'style' => 'Inline',
      ],
      'match' => [
        'name',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_seminar_zusatzinfo_CustomField_seminar_interne_anmerkungen',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'seminar_zusatzinfo',
        'name' => 'seminar_interne_anmerkungen',
        'label' => E::ts('Interne Anmerkungen'),
        'data_type' => 'Memo',
        'html_type' => 'TextArea',
        'is_searchable' => TRUE,
        'attributes' => 'rows=4, cols=60',
        'column_name' => 'seminar_interne_anmerkungen',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_seminar_zusatzinfo_CustomField_seminar_seminarzeiten',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'seminar_zusatzinfo',
        'name' => 'seminar_seminarzeiten',
        'label' => E::ts('Seminarzeiten'),
        'data_type' => 'Memo',
        'html_type' => 'RichTextEditor',
        'is_searchable' => TRUE,
        'column_name' => 'seminar_seminarzeiten',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_seminar_zusatzinfo_CustomField_seminar_hinweise',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'seminar_zusatzinfo',
        'name' => 'seminar_hinweise',
        'label' => E::ts('Hinweise zum Seminar'),
        'data_type' => 'Memo',
        'html_type' => 'RichTextEditor',
        'is_searchable' => TRUE,
        'column_name' => 'seminar_hinweise',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_seminar_zusatzinfo_CustomField_seminar_sc_event_id',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'seminar_zusatzinfo',
        'name' => 'seminar_sc_event_id',
        'label' => E::ts('Social-Scout Event ID'),
        'html_type' => 'Text',
        'is_searchable' => TRUE,
        'column_name' => 'seminar_sc_event_id',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_seminar_durchf_hrungsart',
    'entity' => 'OptionGroup',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'seminar_durchf_hrungsart',
        'title' => E::ts('Durchführungsart von Seminaren'),
        'description' => E::ts('Durchführungsart von Seminaren'),
        'option_value_fields' => [
          'name',
          'label',
          'description',
        ],
      ],
      'match' => [
        'name',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_seminar_durchf_hrungsart_OptionValue_pr_senz',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'seminar_durchf_hrungsart',
        'label' => E::ts('Präsenz'),
        'value' => '1',
        'name' => 'präsenz',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_seminar_durchf_hrungsart_OptionValue_online',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'seminar_durchf_hrungsart',
        'label' => E::ts('Online'),
        'value' => '2',
        'name' => 'online',
        'is_default' => TRUE,
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_seminar_zusatzinfo_CustomField_seminar_durchf_hrungsart',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'seminar_zusatzinfo',
        'name' => 'seminar_durchf_hrungsart',
        'label' => E::ts('Durchführungsart'),
        'html_type' => 'Select',
        'is_searchable' => TRUE,
        'column_name' => 'seminar_durchf_hrungsart',
        'option_group_id.name' => 'seminar_durchf_hrungsart',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_seminar_thema',
    'entity' => 'OptionGroup',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'seminar_thema',
        'title' => E::ts('Seminarthema'),
        'description' => E::ts('Thema des Seminars'),
        'option_value_fields' => [
          'name',
          'label',
          'description',
        ],
      ],
      'match' => [
        'name',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_seminar_thema_OptionValue_umweltschutz',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'seminar_thema',
        'label' => E::ts('Umweltschutz'),
        'value' => '1',
        'name' => 'umweltschutz',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_seminar_thema_OptionValue_oeffentlichkeitsarbeit',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'seminar_thema',
        'label' => E::ts('Öffentlichkeitsarbeit'),
        'value' => '2',
        'name' => 'oeffentlichkeitsarbeit',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_seminar_thema_OptionValue_umweltbildung',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'seminar_thema',
        'label' => E::ts('Umweltbildung'),
        'value' => '3',
        'name' => 'umweltbildung',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_seminar_thema_OptionValue_vielfalt',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'seminar_thema',
        'label' => E::ts('Vielfalt'),
        'value' => '4',
        'name' => 'vielfalt',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_seminar_thema_OptionValue_sonstiges',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'seminar_thema',
        'label' => E::ts('Sonstiges'),
        'value' => '5',
        'name' => 'sonstiges',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_seminar_zusatzinfo_CustomField_seminar_thema',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'seminar_zusatzinfo',
        'name' => 'seminar_thema',
        'label' => E::ts('Thema'),
        'html_type' => 'Select',
        'is_searchable' => TRUE,
        'column_name' => 'seminar_thema',
        'option_group_id.name' => 'seminar_thema',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_seminar_region',
    'entity' => 'OptionGroup',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'seminar_region',
        'title' => E::ts('Regionalstellen'),
        'description' => E::ts('Regionalstellen'),
        'option_value_fields' => [
          'name',
          'label',
          'description',
        ],
      ],
      'match' => [
        'name',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_seminar_region_OptionValue_seminar_s_d',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'seminar_region',
        'label' => E::ts('Süd'),
        'value' => '1',
        'name' => 'seminar_s_d',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_seminar_region_OptionValue_seminar_ost',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'seminar_region',
        'label' => E::ts('Ost'),
        'value' => '2',
        'name' => 'seminar_ost',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_seminar_region_OptionValue_seminar_west',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'seminar_region',
        'label' => E::ts('West'),
        'value' => '3',
        'name' => 'seminar_west',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_seminar_region_OptionValue_seminar_nord',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'seminar_region',
        'label' => E::ts('Nord'),
        'value' => '4',
        'name' => 'seminar_nord',
        'is_default' => TRUE,
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_seminar_zusatzinfo_CustomField_seminar_region',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'seminar_zusatzinfo',
        'name' => 'seminar_region',
        'label' => E::ts('Region'),
        'html_type' => 'Select',
        'is_searchable' => TRUE,
        'column_name' => 'seminar_region',
        'option_group_id.name' => 'seminar_region',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_seminar_zusatzinfo_CustomField_seminar_gesamtzahl_tage',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'seminar_zusatzinfo',
        'name' => 'seminar_gesamtzahl_tage',
        'label' => E::ts('Gesamtzahl Seminartage'),
        'data_type' => 'Int',
        'html_type' => 'Text',
        'is_searchable' => TRUE,
        'is_search_range' => TRUE,
        'column_name' => 'seminar_gesamtzahl_tage',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_seminar_zusatzinfo_CustomField_Maximalbelegung',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'seminar_zusatzinfo',
        'name' => 'Maximalbelegung',
        'label' => E::ts('Maximalbelegung'),
        'data_type' => 'Int',
        'html_type' => 'Text',
        'is_searchable' => TRUE,
        'is_search_range' => TRUE,
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'maximalbelegung',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_seminar_zusatzinfo_CustomField_seminar_nur_f_r_vollj_hrige',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'seminar_zusatzinfo',
        'name' => 'seminar_nur_f_r_vollj_hrige',
        'label' => E::ts('Seminar nur für Volljährige'),
        'data_type' => 'Boolean',
        'html_type' => 'Radio',
        'is_searchable' => TRUE,
        'column_name' => 'seminar_nur_f_r_vollj_hrige',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_seminar_zusatzinfo_CustomField_seminar_gesamtkosten',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'seminar_zusatzinfo',
        'name' => 'seminar_gesamtkosten',
        'label' => E::ts('Gesamtkosten'),
        'data_type' => 'Money',
        'html_type' => 'Text',
        'is_searchable' => TRUE,
        'column_name' => 'seminar_gesamtkosten',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_seminar_zusatzinfo_CustomField_Honorarkosten',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'seminar_zusatzinfo',
        'name' => 'Honorarkosten',
        'label' => E::ts('Honorarkosten'),
        'data_type' => 'Money',
        'html_type' => 'Text',
        'is_searchable' => TRUE,
        'is_search_range' => TRUE,
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'honorarkosten',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_seminar_zusatzinfo_CustomField_Raumkosten',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'seminar_zusatzinfo',
        'name' => 'Raumkosten',
        'label' => E::ts('Raumkosten'),
        'data_type' => 'Money',
        'html_type' => 'Text',
        'is_searchable' => TRUE,
        'is_search_range' => TRUE,
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'raumkosten',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_seminar_zusatzinfo_CustomField_Verpfelgungskosten',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'seminar_zusatzinfo',
        'name' => 'Verpfelgungskosten',
        'label' => E::ts('Verpflegungskosten'),
        'data_type' => 'Money',
        'html_type' => 'Text',
        'is_searchable' => TRUE,
        'is_search_range' => TRUE,
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'verpfelgungskosten',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_seminar_zusatzinfo_CustomField_Sonstige_Kosten',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'seminar_zusatzinfo',
        'name' => 'Sonstige_Kosten',
        'label' => E::ts('Sonstige Kosten'),
        'data_type' => 'Money',
        'html_type' => 'Text',
        'is_searchable' => TRUE,
        'is_search_range' => TRUE,
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'sonstige_kosten',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
];
